spring.application.name=java-spring-practice

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_practice
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=user
spring.datasource.password=
spring.jpa.show-sql=true

spring.jpa.open-in-view=false